# Generated by Django 4.0.4 on 2022-11-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanWater', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=10000)),
                ('date', models.DateField()),
            ],
        ),
    ]
