# Generated by Django 4.0.4 on 2022-11-01 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cleanWater', '0003_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='briefDesc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
