# Generated by Django 4.0.4 on 2022-11-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanWater', '0005_alter_articles_options_alter_articles_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
